#!/usr/bin/env python3
"""Draw Quest tasks as a Mermaid dependency or milestone diagram, from Quest's own JSON.

Plan diagrams are generated, never hand-drawn, so every node and edge is true
by construction: nodes are the tasks Quest returns, edges are their
`dependencies` (prerequisite --> the task it unblocks), and every node carries
a `%% ref` line that diagram_truth.py can re-check later.

Usage:
    quest_graph.py deps       [filters] [--level L] [--title T] [--markdown]
    quest_graph.py milestones [filters] [--level L] [--title T] [--markdown]

Filters (passed to `quest task list`): --status, --label, --milestone, --parent.
--ids A,B,C keeps only those tasks. --open drops terminal-status tasks.
--input FILE reads a saved `quest task list --json` envelope instead of calling quest.
--input-milestones FILE does the same for `quest milestone list --json`.

Exit codes: 0 ok, 2 usage or quest error, 3 more tasks than the level's node
cap (narrow the filters, or pass --level advanced; the cap is the point).
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from diagram_lint import NODE_CAPS  # noqa: E402

TERMINAL = {"done", "closed"}
# Status classes: colour is backed by a line style and by the status word in the
# label, so the diagram still reads in greyscale (WCAG 1.4.1). Fills are light
# with near-black text (contrast > 12:1); strokes are >= 3:1 against the fill.
STATUS_CLASS = {
    "done": ("done", "fill:#e6f4ea,stroke:#1e6b34,stroke-width:1px,color:#111"),
    "in progress": ("doing", "fill:#fff4d6,stroke:#8a5a00,stroke-width:3px,color:#111"),
    "paused": ("paused", "fill:#f1f1f1,stroke:#555,stroke-width:1px,stroke-dasharray:2 2,color:#111"),
    "closed": ("closed", "fill:#f1f1f1,stroke:#555,stroke-width:1px,stroke-dasharray:2 2,color:#111"),
}
TODO_CLASS = ("todo", "fill:#ffffff,stroke:#1f4e8c,stroke-width:1px,stroke-dasharray:6 3,color:#111")
LEGEND = {
    "done": "thin solid border, green: done",
    "doing": "thick border, amber: in progress",
    "todo": "dashed border: to do",
    "paused": "dotted border, grey: paused",
    "closed": "dotted border, grey: closed without being done",
}


def run_quest(args: list[str]) -> list[dict]:
    try:
        r = subprocess.run(["quest", *args, "--json"], capture_output=True, text=True, timeout=120)
    except OSError as e:
        raise SystemExit(f"quest not runnable: {e}")
    if r.returncode != 0:
        print(r.stdout or r.stderr, file=sys.stderr)
        raise SystemExit(2)
    return json.loads(r.stdout)["data"]


def load(path: str | None, quest_args: list[str]) -> list[dict]:
    if path:
        doc = json.loads(Path(path).read_text())
        return doc["data"] if isinstance(doc, dict) else doc
    return run_quest(quest_args)


def node_id(task_id: str) -> str:
    return re.sub(r"\W", "_", task_id)


def label(t: dict, width: int = 42) -> str:
    title = t.get("title", "")
    if len(title) > width:
        title = title[: width - 1].rstrip() + "…"
    text = f"{t['id']}: {title} ({t.get('status', '?').lower()})"
    return text.replace('"', "#quot;")


def status_class(t: dict) -> tuple[str, str]:
    return STATUS_CLASS.get(str(t.get("status", "")).lower(), TODO_CLASS)


def render(tasks: list[dict], view: str, title: str, level: str, milestones: list[dict]) -> tuple[str, str]:
    ids = {t["id"] for t in tasks}
    edges = [(d, t["id"]) for t in tasks for d in (t.get("dependencies") or []) if d in ids]
    counts: dict[str, int] = {}
    for t in tasks:
        k = status_class(t)[0]
        counts[k] = counts.get(k, 0) + 1
    summary = ", ".join(f"{n} {k.replace('doing', 'in progress').replace('todo', 'to do')}" for k, n in sorted(counts.items()))
    lines = [
        "flowchart LR",
        f"  accTitle: {title}",
        f"  accDescr: {len(tasks)} Quest tasks ({summary}) and the {len(edges)} dependencies between them. Each arrow points from a prerequisite to the task it unblocks.",
        f"  %% level: {level}",
        "  %% edges: quest-dependencies",
        "  %% generated by quest_graph.py from quest task list --json; regenerate rather than hand-edit",
    ]
    by_ms: dict[str, list[dict]] = {}
    if view == "milestones":
        member = {tid: m["id"] for m in milestones for tid in (m.get("taskIds") or [])}
        for t in tasks:
            ms = t.get("milestoneId") or member.get(t["id"]) or ""
            by_ms.setdefault(ms, []).append(t)
        names = {m["id"]: m.get("title", m["id"]) for m in milestones}
        for ms, group in sorted(by_ms.items(), key=lambda kv: (kv[0] == "", kv[0])):
            if ms:
                ms_title = str(names.get(ms, ms)).replace('"', "#quot;")
                lines.append(f'  subgraph {node_id(ms)}["{ms}: {ms_title}"]')
            else:
                lines.append('  subgraph no_milestone["No milestone"]')
            lines += [f'    {node_id(t["id"])}["{label(t)}"]' for t in group]
            lines.append("  end")
    else:
        lines += [f'  {node_id(t["id"])}["{label(t)}"]' for t in tasks]
    lines += [f"  {node_id(a)} --> {node_id(b)}" for a, b in edges]
    used = {}
    for t in tasks:
        name, style = status_class(t)
        used.setdefault(name, (style, []))[1].append(node_id(t["id"]))
    for name, (style, members) in sorted(used.items()):
        lines.append(f"  classDef {name} {style}")
        lines.append(f"  class {','.join(members)} {name}")
    lines += [f'  %% ref {node_id(t["id"])} = quest:{t["id"]}' for t in tasks]
    legend = "Legend: " + "; ".join(LEGEND[n] for n in sorted(used)) + ". The status is also written in each box."
    return "\n".join(lines) + "\n", legend


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n")[0])
    ap.add_argument("view", choices=["deps", "milestones"])
    for f in ("status", "label", "milestone", "parent"):
        ap.add_argument(f"--{f}")
    ap.add_argument("--ids", help="comma-separated task ids to keep")
    ap.add_argument("--open", action="store_true", help="drop tasks in a terminal status")
    ap.add_argument("--level", choices=sorted(NODE_CAPS), default="intermediate")
    ap.add_argument("--title")
    ap.add_argument("--markdown", action="store_true", help="wrap in a ```mermaid fence and print the legend line")
    ap.add_argument("--input")
    ap.add_argument("--input-milestones")
    a = ap.parse_args(argv)

    qargs = ["task", "list"]
    for f in ("status", "label", "milestone", "parent"):
        if getattr(a, f):
            qargs += [f"--{f}", getattr(a, f)]
    tasks = load(a.input, qargs)
    if a.ids:
        keep = {s.strip() for s in a.ids.split(",")}
        tasks = [t for t in tasks if t["id"] in keep]
    if a.open:
        tasks = [t for t in tasks if str(t.get("status", "")).lower() not in TERMINAL]
    tasks.sort(key=lambda t: [int(x) if x.isdigit() else x for x in re.split(r"(\d+)", t["id"])])
    if not tasks:
        print("no tasks match the filters", file=sys.stderr)
        return 2
    cap = NODE_CAPS[a.level]
    if len(tasks) > cap:
        print(f"{len(tasks)} tasks exceed the {a.level} cap of {cap}. Narrow with --open, --parent, --label, "
              f"--milestone or --ids, or draw one diagram per milestone.", file=sys.stderr)
        return 3
    milestones = []
    if a.view == "milestones":
        milestones = load(a.input_milestones, ["milestone", "list"]) if (a.input_milestones or not a.input) else []
    title = a.title or ("Task dependencies" if a.view == "deps" else "Tasks by milestone")
    mermaid, legend = render(tasks, a.view, title, a.level, milestones)
    if a.markdown:
        print(f"```mermaid\n{mermaid}```\n\n{legend}")
    else:
        print(mermaid, end="")
        print(legend, file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
